[platformio]
default_envs = production

[env]
monitor_speed = 500000

[env:hall-validation]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
build_src_filter =
    -<*>
    +<hall_validation/>

[env:simplefoc-hall-validation]
extends = env:hall-validation
build_flags =
    -DHALL_USE_SIMPLEFOC=1
lib_deps =
    askuric/Simple FOC @ 2.4.0

[env:motor-smoke]
extends = env:hall-validation
build_src_filter =
    -<*>
    +<motor_smoke/>
lib_deps =
    askuric/Simple FOC @ 2.4.0

[env:motor-tuning]
extends = env:hall-validation
build_src_filter =
    -<*>
    +<motor_tuning/>
lib_deps =
    askuric/Simple FOC @ 2.4.0

[env:production]
extends = env:hall-validation
build_src_filter =
    -<*>
    +<production/>
lib_deps =
    askuric/Simple FOC @ 2.4.0
